services:
  postgres:
    image: postgres:15.17-trixie
    container_name: payments-postgres
    restart: unless-stopped
    env_file:
      - local.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s

  rabbitmq:
    image: rabbitmq:4.1-management
    container_name: payments-rabbitmq
    restart: unless-stopped
    env_file:
      - local.env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  rabbitmq_data:
