from typing import Protocol

from payments.entities.entities import OutboxEvent


class OutboxProcessorGateway(Protocol):
    async def get_waiting(self, limit: int = 100) -> list[OutboxEvent]: ...
    async def update_sent_status(self, event: OutboxEvent) -> None: ...
    async def delete_old(self) -> int: ...
